// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrBvkAiSEu7sq7D838cO-vlY13USls_lo',
    appId: '1:135922194001:web:cee446b3bd7af26dd88a70',
    messagingSenderId: '135922194001',
    projectId: 'fir-ea35c',
    authDomain: 'fir-ea35c.firebaseapp.com',
    storageBucket: 'fir-ea35c.firebasestorage.app',
    measurementId: 'G-ZRE3QPWDCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnBgDQxFpF_kRnMWKAMAgkLmJobHANjY8',
    appId: '1:135922194001:android:fd42ba52226d10e5d88a70',
    messagingSenderId: '135922194001',
    projectId: 'fir-ea35c',
    storageBucket: 'fir-ea35c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJAO1f4UUW2S0j0kh-UnM5H0bXmqAOvkM',
    appId: '1:135922194001:ios:701feb5ecbf87270d88a70',
    messagingSenderId: '135922194001',
    projectId: 'fir-ea35c',
    storageBucket: 'fir-ea35c.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJAO1f4UUW2S0j0kh-UnM5H0bXmqAOvkM',
    appId: '1:135922194001:ios:701feb5ecbf87270d88a70',
    messagingSenderId: '135922194001',
    projectId: 'fir-ea35c',
    storageBucket: 'fir-ea35c.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrBvkAiSEu7sq7D838cO-vlY13USls_lo',
    appId: '1:135922194001:web:d809b333d17984f9d88a70',
    messagingSenderId: '135922194001',
    projectId: 'fir-ea35c',
    authDomain: 'fir-ea35c.firebaseapp.com',
    storageBucket: 'fir-ea35c.firebasestorage.app',
    measurementId: 'G-BLKJ6R2NQS',
  );
}
